site_name: USTC 编译原理和技术 2024
repo_name: USTC-Compiler-2024/HomePage
repo_url: https://github.com/USTC-Compiler-2024/HomePage

theme:
  custom_dir: overrides
  name: material
  language: 'zh'
  features:
    - navigation.tabs     # 启用上方的分栏
    - navigation.tabs.sticky  # 让分栏保持可见
    - navigation.expand   # 启用左侧导航栏的展开按钮
    - navigation.footer   # 启用界面下方翻页按钮
    - content.code.copy   # 启用代码框复制按钮

  icon:
    # 对应网址为 https://fontawesome.com/
    logo: fontawesome/solid/computer
    repo: fontawesome/brands/github

  palette:
    - scheme: 'default'
      primary: 'deep purple'
      accent: 'deep purple'
      toggle:
        icon: material/weather-sunny
        name: 切换到夜晚模式
    - scheme: 'slate'
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-night
        name: 切换到白天模式

plugins:
  - search
  - glightbox
  - git-authors   # 显示作者 https://github.com/timvink/mkdocs-git-authors-plugin
  - git-revision-date-localized   # 显示上次编辑时间 https://github.com/timvink/mkdocs-git-revision-date-localized-plugin





markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - admonition
  - pymdownx.keys

  - pymdownx.blocks.admonition: # 不同风格的提示块
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True


extra_css:
  - stylesheets/extra.css
  - css/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
# 下面是完整的目录

nav:
  - 首页: index.md
  - 课程平台介绍: exp_platform_intro/README.md
  # - 公共文档:
  #   - Cminusf 语法语义介绍: common/cminusf.md
  #   - Light IR 简介: common/LightIR.md
  #   - C++ 介绍: common/simple_cpp.md
  #   - Logging 工具使用: common/logging.md
  #   - 龙芯汇编介绍: common/asm_intro.md
  # - Lab0:
  #   - Lab0 简介: lab0/index.md
  #   - Linux 环境配置: lab0/linux.md
  #   - LLVM 等软件环境配置: lab0/software.md
  #   - Git 的使用: lab0/git.md
  # - Lab1:
  #   - Lab1 简介: lab1/index.md
  #   - 正则表达式: lab1/正则表达式.md
  #   - Flex: lab1/Flex.md
  #   - Bison: lab1/Bison.md
  #   - 实验细节与要求: lab1/实验细节与要求.md
  # - Lab2:
  #   - Lab2 简介: lab2/index.md
  #   - Light IR 预热: lab2/warmup.md
  #   - 访问者模式: lab2/visitor_pattern.md
  #   - IR 自动化生成: lab2/autogen.md
  # - Lab3:
  #   - Lab3 简介: lab3/index.md
  #   - Lab3 实验指导: lab3/guidance.md
  #   - 后端环境配置: lab3/environment.md
  #   - 龙芯汇编介绍: common/asm_intro.md
  #   - 栈式分配介绍: lab3/stack_allocation.md
  #   - 后端框架介绍: lab3/framework.md
  # - Lab4: lab4/index.md
  # - 建木杯–编译原理创新实验: innovative-lab/index.md
  # - FAQ: faq/README.md

